version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:471112955271:task-definition/springdemo:5"
        LoadBalancerInfo:
          ContainerName: "SpringDemo"
          ContainerPort: 80
        PlatformVersion: "LATEST"
#
Hooks:
  - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:471112955271:function:AfterAllowTestTraffic"