# File: utils.yaml 
# This module create all the utility resources like sns, eventbridge etc 
#
# Before executing this, make sure "init.sh" is called which would create all "Parameter Store"  
#
# Resource that would be created
# 1) SNS Topic 
# 

Description: "Create Utility Resources"

Parameters: 
  networkStackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: nw

  permStackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: perm

  environment: 
    Type: String 
    Default: dev 
    AllowedValues: 
      - dev
      - prod 
    
Resources:
    # Create CodeBuild Bucket for storing build artifacts    
    # Inputs: 
    #  From Parameter store
    #  1) codebuild build prefix  
    #   
  myTopic:
    Description: "Create SNS Topic"
    Type: AWS::SNS::Topic
    Properties:
      TopicName: myTopic 
      
      Tags:
       - Key: Name
         Value: !Join [" - ", [Fn::Sub: "${AWS::StackName}", "bucket "] ]
       - Key: Environment
         Value: !Sub ${environment}	
  
# Outputs     
# 1) SNS Topic ARN  
# 
Outputs:
  SNSTopicArn:
    Value: !Ref myTopic
    Export:
      "Name" :
        Fn::Sub: "${AWS::StackName}-SNS-TOPIC-ARN"



