version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:975050342959:task-definition/springdemo:1"
        LoadBalancerInfo:
          ContainerName: "SpringDemo"
          ContainerPort: 80
        PlatformVersion: "LATEST"
#
Hooks:
  - BeforeInstall: "BeforeInstall"
  - AfterInstall: "AfterInstall"
  - AfterAllowTestTraffic: "AfterAllowTestTraffic"
  - BeforeAllowTraffic: "BeforeAllowTraffic"
  - AfterAllowTraffic: "AfterAllowTraffic"
  